### PR TITLE
Rename FactoryBot

### PR DESCRIPTION
**Pull request by tvdeyen**

### CODE REVIEW

**Review by mamhoff — APPROVED** [review]

**Comment by tvdeyen** [comment]
https://travis-ci.org/solidusio/solidus_paypal_braintree/jobs/292006204

**Comment by tvdeyen** [comment]
Needed for https://github.com/solidusio/solidus_paypal_braintree/pull/131

**Review by mamhoff — APPROVED** [review]

**Comment by jhawthorn** [comment]
I'm not sure this will work for older versions of Solidus, which will expect the `FactoryGirl` constant to exist. Will follow up with a second PR if a change is necessary

**Comment by jhawthorn** [comment]
Because older versions will `require 'factory_girl'`, no adjustment was necessary :ok_hand:.

**Comment by tvdeyen** [comment]
🤘🏻

**Pull request merged**
