### PR TITLE
Remove running rubocop on rake task

### PR DESCRIPTION
**Pull request by kennyadsl**
As pointed out [here](https://github.com/solidusio/solidus_support/pull/13#pullrequestreview-162995245) this is something worth a discussion at least. Sorry for merging without a review!

### CODE REVIEW

**Comment by kennyadsl** [comment]
@tvdeyen ^

**Review by tvdeyen — APPROVED** [review]
Thanks 🍰

**Comment by kennyadsl** [comment]
@solidusio/core-team can I have another review here? 🙂

**Review by jacobherrington — APPROVED** [review]
I agree with @tvdeyen in the discussion, we should use Hound if possible.

**Pull request merged**
