### PR TITLE
Add support for Codecov

### PR DESCRIPTION
**Pull request by aldesantis**
Adds a SimpleCov/Codecov configuration to automatically track code coverage for extensions in [codecov.io](https://codecov.io)!

### CODE REVIEW

**Comment by kennyadsl** [comment]
Can you please describe which steps are required to be made into each extension to make it work?

**Comment by aldesantis** [comment]
@kennyadsl basically just what it says on the readme. Require the file at the top of spec_helper and that's it. Then we can add the badge to the readme if we want and/or make the PR check required.

**Review by kennyadsl — APPROVED** [review]
@solidusio/core-team can we have a second review/opinion here?

**Review by spaghetticode — APPROVED** [review]
I think this is a good idea, as more coverage usually translates into more confidence in the code reliability. Thank you @aldesantis 👍

**Pull request merged**
